# Change directory to node red directory
Set-Location "$env:HomeDrive\Users\$env:UserName\.node-red"
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Installing PLC communications..."
Write-Host ""
Write-Host ""
Write-Host ""
npm install  --no-audit --no-update-notifier --no-fund --save node-red-contrib-cip-ethernet-ip
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "PLC communications installation complete."
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Installing SQLite database support..."
Write-Host ""
Write-Host ""
Write-Host ""
install  --no-audit --no-update-notifier --no-fund --save node-red-node-sqlite
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "SQLite database support installation complete."
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Installing CPU diagnostics..."
Write-Host ""
Write-Host ""
Write-Host ""
npm install  --no-audit --no-update-notifier --no-fund --save node-red-contrib-cpuWrite-Host ""
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "CPU diagnostics installation complete."
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Installing operating system diagnostics..."
Write-Host ""
Write-Host ""
install  --no-audit --no-update-notifier --no-fund --save node-red-contrib-os
Write-Host ""
Write-Host ""
Write-Host ""
Write-Host "Operating System diagnostics installation complete."
Write-Host ""
Start-Process $pwd\task.cmd